---
- name: Developing stand configuration
  hosts: dev01
  become: yes

  roles:
    - common
    - security
    - dev_stand

- name: Production stand configuration
  hosts: prod01
  become: yes

  roles:
    - common
    - security
    - prod_stand
