---
# tasks file for security
- name: Adding banner info in sshd.conf
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: '#Banner /etc/ssh/banner'
    line: "Banner /etc/ssh/banner"

- name: Update ssh banner
  template:
    src: banner.j2
    dest: /etc/ssh/banner
  tags:
    - ssh-banner-configuration

- name: Restart ssh
  service: name=ssh state=restarted