---
# tasks file for prod_stand

# tasks for installing tomcat
- name: Create folder
  file:
    path: "{{ playbook_dir }}/tomcat"
    state: directory
    mode: 0755
    owner: root
    group: root

- name: Download Tomcat
  get_url: url=https://archive.apache.org/dist/tomcat/tomcat-8/v8.5.9/bin/apache-tomcat-8.5.9.tar.gz dest="{{ playbook_dir }}/tomcat"

- name: Extract archive
  unarchive:
    src: "{{ playbook_dir }}/tomcat/apache-tomcat-8.5.9.tar.gz"
    dest: "{{ playbook_dir }}/tomcat"
    remote_src: yes

- name: start apache-tomcat
  command: nohup "{{ playbook_dir }}/tomcat/apache-tomcat-8.5.9/bin/startup.sh"

- name: Copy file from dev_stand to prod_stand
  become: yes
  shell: rsync -avzh root@{ hostvars['dev01'].ansible_host }}:{{ playbook_dir }}/boxfuse/target/ {{ playbook_dir }}/tomcat/apache-tomcat-8.5.9/webapps/
#  synchronize:
#    mode: pull
#    src: "rsync://{{ hostvars['dev01'].ansible_host }}{{ playbook_dir }}/boxfuse/target/"
#   dest: "{{ playbook_dir }}/tomcat/apache-tomcat-8.5.9/webapps/"
#    rsync_path: su -c rsync


#    src: "{{ playbook_dir }}/boxfuse/target/"
#     dest: "rsync://{{ ['prod']['ansible_host'] }}/{{ playbook_dir }}/tomcat/apache-tomcat-8.5.9/webapps"