---
# tasks file for common
- name: Install packages
  become: yes
  apt: pkg={{ item }} state=latest update_cache=yes cache_valid_time=3600
  with_items:
    - mc
    - htop
    - ncdu
    - tree
    - links
    - rsync